Repository ripio/rcn-loans, pull requests merged in 2018-09, with the labels that each got.

#92 styling revert #87
  src/app/views/loan-detail/transaction-history/transaction-history.component.scss
Labels: invalid

#94 Navigation
  src/app/services/previousRoute.service.ts
  src/app/shared/detail-button/detail-button.component.ts
  src/app/shared/shared.module.ts
  src/app/views/loan-detail/loan-detail.component.ts
  src/app/views/loan-detail/loan-detail.module.ts
Labels: bug

#100 Updated Decentraland mortgages contracts for Mainnet
  src/environments/cosigners.ts
  src/environments/environment.prod.ts
Labels: configuration

#101 Footer Version displaying
  src/app/content-wrapper/content-wrapper.component.html
  src/app/content-wrapper/content-wrapper.component.ts
  src/app/core/footer/footer.component.html
  src/styles.scss
Labels: bug

#103 Transaction history
  src/app/views/loan-detail/transaction-history/transaction-history.component.html
Labels: bug

#106 Claim cosigner button fix
  src/app/providers/cosigners/decentraland-cosigner-provider.ts
  src/app/views/loan-detail/detail-cosigner/decentraland-cosigner/decentraland-cosigner.component.html
  src/app/views/loan-detail/detail-cosigner/decentraland-cosigner/decentraland-map/decentraland-map.component.html
Labels: bug

#107 Bootstrap migrationv4
  angular.json
  package.json
  src/app/active-loans/active-loans.component.html
  src/app/content-wrapper/content-wrapper.component.scss
  src/app/content-wrapper/content-wrapper.component.ts
  src/app/core/footer/footer.component.html
  src/app/dialogs/dialog-approve-contract/dialog-approve-contract.component.html
  src/app/dialogs/dialog-client-account/dialog-client-account.component.html
  src/app/dialogs/dialog-generic-error/dialog-generic-error.component.html
  src/app/dialogs/dialog-insufficient-founds/dialog-insufficient-founds.component.html
  src/app/dialogs/dialog-loan-transfer/dialog-loan-transfer.component.html
  src/app/header/header.component.html
  src/app/header/header.component.scss
  src/app/shared/avatar-title/avatar-title.component.html
  src/app/shared/avatar-title/avatar-title.component.scss
  src/app/shared/avatar-title/icon-avatar/icon-avatar.component.scss
  src/app/shared/button-group/button-group.component.html
  src/app/shared/button-group/button-group.component.scss
  src/app/shared/conversion-graphic/body-list/body-list.component.html
  src/app/shared/conversion-graphic/body-list/body-list.component.scss
  src/app/shared/conversion-graphic/header-list/header-list.component.html
  src/app/shared/conversion-graphic/header-list/header-list.component.scss
  src/app/shared/cosigner-selector/cosigner-selector.component.scss
  src/app/shared/goback-button/goback-button.component.scss
  src/app/shared/loan-avatar/loan-avatar.component.html
  src/app/shared/loan-avatar/loan-avatar.component.scss
  src/app/shared/loan-card/loan-card.component.html
  src/app/shared/loan-card/loan-card.component.scss
  src/app/shared/transfer-form/transfer-form.component.html
  src/app/views/address/address.component.html
  src/app/views/loan-detail/detail-cosigner/decentraland-cosigner/decentraland-cosigner.component.html
  src/app/views/loan-detail/detail-cosigner/detail-cosigner.component.scss
  src/app/views/loan-detail/detail-identity/detail-identity.component.html
  src/app/views/loan-detail/detail-identity/detail-identity.component.scss
  src/app/views/loan-detail/detail-table/detail-table.component.scss
  src/app/views/loan-detail/loan-detail.component.html
  src/app/views/loan-detail/loan-detail.component.scss
  src/app/views/loan-detail/loan-detail.component.ts
  src/app/views/open-loans/open-loans.component.html
  src/app/views/profile/profile.component.html
  src/index.html
  src/scss/_helpers.scss
  src/scss/_tables.scss
  src/scss/_variables.scss
  src/styles.scss
Labels: enhancement, feature, optimization
