Repository ripio/rcn-loans, pull requests merged in 2018-08, with the labels that each got.

#52 Fix civic popup
  src/app/services/civic.service.ts
Labels: bug

#56 Hide lend button if loan is not a request
  src/app/shared/loan-card/loan-card.component.html
  src/app/shared/loan-card/loan-card.component.ts
Labels: bug

#57 Angular 6
  package.json
  src/app/content-wrapper/content-wrapper.component.html
  src/styles.scss
  tsconfig.json
Labels: enhancement

#59 Use git suffix as build number
  package.json
  src/environments/build.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  version.js
Labels: enhancement

#60 Sentry bug report
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: feature

#61 Fix withdraw button
  src/app/services/contracts.service.ts
Labels: bug

#68 Add custom color checkbox approve
  src/app/dialogs/dialog-approve-contract/dialog-approve-contract.component.scss
Labels: design

#69 Add analytics tracking
  src/app/app.component.ts
  src/app/shared/lend-button/lend-button.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
Labels: feature

#71 Meta OG path for Twitter/Facebook img
  src/index.html
Labels: enhancement

#75 Sidebar fixes
  src/app/content-wrapper/content-wrapper.component.scss
  src/app/content-wrapper/content-wrapper.component.ts
  src/styles.scss
Labels: enhancement

#77 Fix prod build
  angular.json
  package.json
  patch-crypto.js
  src/app/active-loans/active-loans.component.html
  src/app/active-loans/active-loans.module.ts
  src/app/core/footer/footer.component.html
  src/app/shared/claim-button/claim-button.component.html
  src/app/shared/claim-button/claim-button.component.ts
  src/app/shared/conversion-graphic/body-list/body-list.component.ts
  src/app/shared/loan-card/loan-card.component.ts
  src/app/shared/social-container/social-container.component.ts
  src/app/views/address/address.component.html
  src/app/views/open-loans/open-loans.component.html
Labels: bug

#78 Footer & Header social Height + Responsive mobile fixes
  src/app/content-wrapper/content-wrapper.component.html
  src/app/content-wrapper/content-wrapper.component.ts
  src/app/header/header.component.scss
Labels: bug

#80 Report events GA / Sentry
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/dialogs/dialog-approve-contract/dialog-approve-contract.component.ts
  src/app/services/contracts.service.ts
  src/app/services/events.service.ts
  src/app/shared/lend-button/lend-button.component.ts
  src/app/shared/transfer-button/transfer-button.component.ts
  src/app/tx.service.ts
  src/index.html
Labels: enhancement

#82 Error dialogs
  src/app/app.module.ts
  src/app/dialogs/dialog-generic-error/dialog-generic-error.component.html
  src/app/dialogs/dialog-generic-error/dialog-generic-error.component.scss
  src/app/dialogs/dialog-generic-error/dialog-generic-error.component.ts
  src/app/services/contracts.service.ts
  src/app/services/events.service.ts
  src/app/shared/lend-button/lend-button.component.html
  src/app/shared/lend-button/lend-button.component.ts
  src/app/utils/utils.ts
Labels: enhancement

#83 Loan history
  src/app/app.module.ts
  src/app/header/header.component.scss
  src/app/models/commit.model.ts
  src/app/services/commits.service.ts
  src/app/shared/button-group/button-group.component.html
  src/app/shared/button-group/button-group.component.scss
  src/app/shared/button-group/button-group.component.ts
  src/app/shared/transfer-button/transfer-button.component.scss
  src/app/shared/transfer-button/transfer-button.component.ts
  src/app/views/loan-detail/detail-identity/detail-identity.component.html
  src/app/views/loan-detail/detail-table/detail-table.component.html
  src/app/views/loan-detail/loan-detail.component.html
  src/app/views/loan-detail/loan-detail.module.ts
  src/app/views/loan-detail/transaction-history/transaction-history.component.html
  src/app/views/loan-detail/transaction-history/transaction-history.component.scss
  src/app/views/loan-detail/transaction-history/transaction-history.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/scss/_colors.scss
  src/scss/_fonts.scss
  src/scss/_spaces.scss
  src/styles.scss
Labels: feature
