Repository ripio/rcn-loans, pull requests merged in 2021-05, with the labels that each got.

#674 Feature/UI Adjustments
  src/app/core/header/header.component.scss
  src/app/dialogs/dialog-loan-lend/dialog-loan-lend.component.html
  src/app/dialogs/dialog-loan-lend/dialog-loan-lend.component.scss
  src/app/shared/creator-container/creator-container.component.scss
  src/app/shared/loan-avatar/loan-avatar.component.scss
  src/app/views/requested-loan/requested-loan.component.html
Labels: enhancement

#677 Bugfix/Loan was created
  src/app/services/contracts.service.ts
  src/app/views/create-loan/create-loan.component.ts
Labels: bug

#682 Feature/navrail bullets
  src/app/config/chain/1.ts
  src/app/config/chain/3.ts
  src/app/core/content-wrapper/content-wrapper.component.ts
  src/app/core/navrail/navrail.component.html
  src/app/core/navrail/navrail.component.scss
  src/app/core/navrail/navrail.component.spec.ts
  src/app/core/navrail/navrail.component.ts
  src/app/services/navrail.service.spec.ts
  src/app/services/navrail.service.ts
  src/app/views/address/address.module.ts
  src/app/views/create-loan/create-loan.component.ts
Labels: enhancement

#680 Feature/animations
  .gitignore
  src/app/views/home/home.component.html
  src/app/views/home/home.component.spec.ts
  src/app/views/home/home.component.ts
Labels: WIP

#672 Feature/dashboard
  src/app/app-routing.module.ts
  src/app/core/header/icon-group-header/icon-group-header.component.ts
  src/app/core/navrail/navrail.component.html
  src/app/shared/dashboard-list-header/dashboard-list-header.component.html
  src/app/shared/dashboard-list-header/dashboard-list-header.component.scss
  src/app/shared/dashboard-list-header/dashboard-list-header.component.spec.ts
  src/app/shared/dashboard-list-header/dashboard-list-header.component.ts
  src/app/shared/dashboard-list-item/dashboard-list-item.component.html
  src/app/shared/dashboard-list-item/dashboard-list-item.component.scss
  src/app/shared/dashboard-list-item/dashboard-list-item.component.spec.ts
  src/app/shared/dashboard-list-item/dashboard-list-item.component.ts
  src/app/shared/dashboard-list-skeleton/dashboard-list-skeleton.component.html
  src/app/shared/dashboard-list-skeleton/dashboard-list-skeleton.component.scss
  src/app/shared/dashboard-list-skeleton/dashboard-list-skeleton.component.spec.ts
  src/app/shared/dashboard-list-skeleton/dashboard-list-skeleton.component.ts
  src/app/shared/dashboard-list/dashboard-list.component.html
  src/app/shared/dashboard-list/dashboard-list.component.scss
  src/app/shared/dashboard-list/dashboard-list.component.spec.ts
  src/app/shared/dashboard-list/dashboard-list.component.ts
  src/app/shared/footer/footer.component.html
  src/app/shared/progress-bar/progress-bar.component.html
  src/app/shared/progress-bar/progress-bar.component.scss
  src/app/shared/progress-bar/progress-bar.component.spec.ts
  src/app/shared/progress-bar/progress-bar.component.ts
  src/app/shared/redeem-button/redeem-button.component.html
  src/app/shared/redeem-button/redeem-button.component.scss
  src/app/shared/redeem-button/redeem-button.component.ts
  src/app/shared/shared.module.ts
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.scss
  src/app/views/dashboard/dashboard.component.ts
  src/app/views/dashboard/dashboard.module.ts
  src/app/views/loan-detail/loan-detail.module.ts
  src/app/views/loan-detail/loan-does-not-exist/loan-does-not-exist.component.html
  src/app/views/not-found/not-found.component.html
  src/styles.scss
Labels: feature

#684 Bugfix/loan detail
  src/app/services/tx.service.ts
  src/app/shared/redeem-button/redeem-button.component.ts
  src/app/views/create-loan/step-create-collateral/step-create-collateral.component.ts
  src/app/views/loan-detail/detail-history/detail-history.component.html
  src/app/views/loan-detail/detail-history/detail-history.component.ts
  src/app/views/loan-detail/loan-overview-panel/loan-overview-panel.component.html
  src/app/views/loan-detail/loan-overview-panel/loan-overview-panel.component.ts
Labels: bug, enhancement

#688 Bugfix/usdc decimals
  src/app/dialogs/dialog-collateral/collateral-form/collateral-form.component.ts
  src/app/dialogs/dialog-loan-lend/dialog-loan-lend.component.ts
  src/app/dialogs/dialog-loan-pay/dialog-loan-pay.component.ts
  src/app/services/collateral.service.ts
  src/app/services/currencies.service.ts
  src/app/services/installments.service.spec.ts
  src/app/services/installments.service.ts
  src/app/shared/loan-list/loan-list.component.ts
  src/app/utils/currencies.ts
  src/app/views/create-loan/create-loan-card/create-loan-card.component.ts
  src/app/views/loan-detail/detail-history/detail-history.component.ts
  src/app/views/loan-detail/loan-detail.component.ts
  src/app/views/loan-detail/loan-overview-panel/loan-overview-panel.component.ts
Labels: bug

#689 Bugfix/redeem loading
  src/app/shared/redeem-button/redeem-button.component.html
Labels: enhancement

#687 Bugfix/dashboard responsive
  src/app/shared/dashboard-list-header/dashboard-list-header.component.html
  src/app/shared/dashboard-list-item/dashboard-list-item.component.html
  src/app/views/dashboard/dashboard.component.html
Labels: WIP

#690 Bugfix/dashboard issues
  src/app/shared/dashboard-list-header/dashboard-list-header.component.scss
  src/app/shared/dashboard-list-item/dashboard-list-item.component.html
  src/app/shared/dashboard-list-item/dashboard-list-item.component.scss
  src/app/shared/dashboard-list-item/dashboard-list-item.component.spec.ts
  src/app/shared/dashboard-list-item/dashboard-list-item.component.ts
  src/app/shared/dashboard-list/dashboard-list.component.scss
  src/app/views/dashboard/dashboard.component.scss
  src/styles.scss
Labels: WIP

#691 Feature/dashboard copy
  src/app/shared/dashboard-list-header/dashboard-list-header.component.html
  src/app/shared/dashboard-list-header/dashboard-list-header.component.ts
  src/app/shared/dashboard-list-item/dashboard-list-item.component.html
  src/app/shared/dashboard-list-item/dashboard-list-item.component.ts
  src/app/shared/dashboard-list/dashboard-list.component.html
  src/app/shared/dashboard-list/dashboard-list.component.scss
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.scss
Labels: enhancement

#692 Bugfix/TX redeem
  src/app/core/header/notifications/notifications.component.ts
  src/app/services/tx.service.ts
Labels: bug

#695 Feature/clean code history
  src/app/views/loan-detail/detail-history/detail-history.component.ts
Labels: enhancement

#698 Feature/dashboard tabs
  src/app/shared/dashboard-list-item/dashboard-list-item.component.ts
  src/app/shared/dashboard-list/dashboard-list.component.html
  src/app/shared/dashboard-list/dashboard-list.component.ts
  src/app/views/dashboard/dashboard.component.html
  src/app/views/dashboard/dashboard.component.scss
  src/app/views/dashboard/dashboard.component.ts
Labels: feature

#697 Feature/test dashboard
  src/app/shared/dashboard-list-item/dashboard-list-item.component.html
  src/app/shared/dashboard-list-item/dashboard-list-item.component.spec.ts
  src/app/shared/dashboard-list-item/dashboard-list-item.component.ts
Labels: feature
